version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/random_sikh_facts
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/env.sh
      timeout: 300
      runas: root  
    - location: scripts/after-install.sh
      timeout: 300
      runas: root  
  ApplicationStart:
    - location: scripts/boot.sh
      timeout: 300
      runas: root