# Generated by Django 4.2.3 on 2023-07-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facts",
            name="fact_validated",
            field=models.BooleanField(default=False),
        ),
    ]
