# Generated by Django 4.2.3 on 2023-07-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0002_facts_fact_validated"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Facts",
            new_name="Fact",
        ),
    ]
