# Generated by Django 4.2.3 on 2023-07-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0004_remove_activefact_retrieved_at_fact_retrieved_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fact",
            name="retrieved_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
