# Generated by Django 4.2.3 on 2023-08-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0005_alter_fact_retrieved_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fact",
            name="retrieved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
